### PR TITLE
MRG: Make kmers_and_hashes iterable

### LINKED ISSUE #21: Store hash to kmer map
A common use of kmer counters is to dump kmers and their counts to a text file that can be used in other tools. To do this we need to track hash to kmer pairs.

Suggested solution:

Init `KmerCountTable` objects with a second hashmap that maps hashes to their corresponding canonical kmer sequence.
Add new hash:kmer pairs as kmers are consumed.

To save time and space we could disable this feature by default.

```python
# Enable kmer tracking
new_table = oxli.KmerCountTable(ksize=3, raw=True)
```

Alternative solutions: 

- Could we just use the canonical kmers as keys?

Issues:
- If a kmer is added with `.count_hash` then the kmer sequence is unknown. (maybe just report unpaired hashed as warning when retrieving kmers?)
- If adding KmerCountTables together we would need to also add hash:kmer pairs to the new object (or just add all new hashes into the output table?)
- Tables might get large if consuming large noisy datasets with a high kmer length. (Make kmer tracking optional?)

@ctb thoughts?

### LINKED ISSUE #75: dump_kmers fails after removing records with maxcut
See #74 

Current version of the #70 `integrate_kmer_tracking` branch throws an error if you try to call `dump_kmers()` on a `KmerCountTable` after removing records with maxcut()

Error: 
```
PanicException: called `Option::unwrap()` on a `None` value
```

### PR DESCRIPTION
**Pull request by Adamtaranto**
- [x] Make kmers_and_hashes iterable
- [x] Decide what to do about skip_bad_kmers (force arg in SeqToHashes) - suppress output or error?
- [x] Integrate with `count()` and `consume()`
- [x] Init `KmerCountTable` with option to track kmers
- [x] Add HashMap to store hash:kmer pairs
- [x] Add `unhash()` function
- [x] Add `dump_kmers()` function for sorted kmer,count output
- [x] Make `dump_kmers()` compatible with records dropped by `mincut()`, `maxcut()`, `drop()`, or `drop_hash()`  Close #75

Close #21

### CODE REVIEW

**Comment by Adamtaranto** [comment]
@ctb thoughts on bad kmer handling for this function?

`skip_bad_kmers` is being used to set the `force` option in `SeqToHashes` which decides if bad kmers should halt seq processing or just emit a hash of 0.

When `skip_bad_kmers` is set to `True` our ` kmers_and_hashes` function will still output a blank kmer with hash 0 rather than actually "skipping" it.

I think we should have the `force` option in `SeqToHashes`  permanently  set to `True` and then only use `skip_bad_kmers` to decide if we will output the blank kmer:hash pair as ("",0).

Can you think of any cases where you would want to have `force` set to `False` so that only kmers up to the first bad kmer are processed?

**Comment by ctb** [comment]
I think I agree with you - good point ;)

**Comment by Adamtaranto** [comment]
Ok, I've updated the iterator so it just prints a warning msg to stderr if it sees a bad kmer, and only return includes empty ("",0) in output if `skip_bad_kmers = false`.

If this is too noisy then I guess we could turn off warning if `skip_bad_kmers = true`, though I feel it would be nice to keep as is in case the user does something wacky like try to process protein as DNA.

Can you take a look at the tests? I only know the one method for capturing warning msgs. hammer, nail, etc.

**Comment by Adamtaranto** [comment]
Previous fix for dependabot ruff action GITHUB_TOKEN prevents jobs from restarting after being interrupted by the ruff action.

reverted.

Will need to disable ruff formatting in any actions spawned by dependabot.

**Comment by Adamtaranto** [comment]
@ctb ready for review. Do we want to work on making this faster before merging into main?

Low hanging efficiency fruit:
- [ ] Revcomp the full seq and step through backwards in sliding window to find canonical kmers instead of revcomp per kmer.
- [ ] Make consume multithreaded at the kmer level - both KmersAndHashesIter and SeqToHashes are iterators so this should be fairly simple, unless we are worried about diff threads trying to write to same hash?
- [ ] Make multithreaded at the sequence level?
- [ ] Consume directly from file to avoid having to load seqs in Python and pass back to rust per #10

**Review by ctb — APPROVED** [review]
excellent!

**Comment by Adamtaranto** [comment]
Are we good to merge?

**Comment by ctb** [comment]
yep! go ahead!

**Comment by Adamtaranto** [comment]
Cool, I'll pull in changes from #82 when tests are finished, then merge.

**Pull request merged**
